spring:
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:localhost:9092}
    producer:
      client-id: kafka-message-producer
      acks: all
      value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true #necessary setting
      auto-offset-reset: latest
      group-id: ${consumer.group:group}
#    listener:
#      ack-mode: manual-immediate
    topic:
      rental-record-topic: ${kafka.topic:rental-record-topic}
      rental-record-warning-topic: ${kafka.topic:rental-record-warning-topic}

  data:
    mongodb:
      authentication-database: rental-db
      host: localhost
      port: 29017
      username: root1
      password: root1
      database: rental-db

server:
  error:
    include-message: always