spring:
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:localhost:9092}
    producer:
      client-id: kafka-message-producer
      acks: all
      value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: false #necessary setting
      auto-offset-reset: latest
      group-id: ${consumer.group:group}
    listener:
      ack-mode: manual-immediate
    topic:
      notifications-topic: ${kafka.topic:notifications-topic}

  data:
    mongodb:
      authentication-database: rental-db
      host: localhost
      port: 27020
      username: root1
      password: root1
      database: rental-db