name: Build and Deploy Production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-prod:
    uses: ProductDock/rbc-github-workflows/.github/workflows/build-prod.yml@main
    with:
      update-script: /home/pd-library/update-rental-image.sh
    secrets: inherit